apiVersion: v1
kind: Service
metadata:
  name: comeonda-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000   # Map to container's port 3000
      nodePort: 31322    # Optional: manually specify NodePort
  selector:
    app: comeonda-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comeonda-app  # Changed to use valid RFC 1123 subdomain
spec:
  replicas: 4
  selector:
    matchLabels:
      app: comeonda-app
  template:
    metadata:
      labels:
        app: comeonda-app
    spec:
      containers:
        - name: comeonda
          image: praveen4901/comeondav1:v1
          ports:
            - containerPort: 3000

