apiVersion: v1
kind: Service
metadata:
  name: praveen-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000   # Map to container's port 3000
      nodePort: 31322    # Optional: manually specify NodePort
  selector:
    app: praveen-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: praveen-app  # Changed to use valid RFC 1123 subdomain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: praveen-app
  template:
    metadata:
      labels:
        app: praveen-app
    spec:
      containers:
        - name: comeonda
          image: praveen4901/praveen-app:v1
          ports:
            - containerPort: 3000

